$env:Path += ";$(Resolve-Path ~\Programs\sqlmap)"
$env:Path += ";$(Resolve-Path ~\Programs\sslscan)"
$env:Path += ";C:\Program Files (x86)\nmap"
$env:Path += ";$(Resolve-Path ~\Programs\nikto\program)"

$env:Path += ";$(Resolve-Path ~\Programs\metasploit\ruby\bin)"
$env:Path += ";$(Resolve-Path ~\Programs\metasploit\java\bin)"
$env:Path += ";$(Resolve-Path ~\Programs\metasploit\postgresql\bin)"
$env:Path += ";$(Resolve-Path ~\Programs\metasploit\tools)"
$env:MSF_DATABASE_CONFIG = "$(Resolve-Path ~\Programs\metasploit\apps\pro\ui\config\database.yml)"
$env:BUNDLE_GEMFILE = "$(Resolve-Path ~\Programs\metasploit\apps\pro\ui\Gemfile)"
